//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anbardari2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminTbl
    {
        public int AdminId { get; set; }
        public string AdminName { get; set; }
        public string AdminUserName { get; set; }
        public string AdminUserPassword { get; set; }
        public int AdminRull { get; set; }
    
        public virtual RullTbl RullTbl { get; set; }
    }
}
