//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anbardari2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactorDetailsTbl
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Count { get; set; }
        public double Price { get; set; }
        public int Fk { get; set; }
    
        public virtual FactorTbl FactorTbl { get; set; }
    }
}
