//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anbardari2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactorSellTbl
    {
        public int FactorSellId { get; set; }
        public string FactorSellCode { get; set; }
        public System.DateTime FactorSubmitTime { get; set; }
    }
}
