//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anbardari2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactorProductSellListTbl
    {
        public int FactorId { get; set; }
        public string name { get; set; }
        public int count { get; set; }
        public double price { get; set; }
        public int fk { get; set; }
    }
}
