//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anbardari2
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTbl
    {
        public int InventoryId { get; set; }
        public string OperatorName { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public double ProductPrice { get; set; }
        public int number { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public string ProductCode { get; set; }
    }
}
