//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anbardari2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgainOstaniDbEntities : DbContext
    {
        public AgainOstaniDbEntities()
            : base("name=AgainOstaniDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTbl> AdminTbls { get; set; }
        public virtual DbSet<CustomerTbl> CustomerTbls { get; set; }
        public virtual DbSet<FactorDetailsTbl> FactorDetailsTbls { get; set; }
        public virtual DbSet<FactorProductSellListTbl> FactorProductSellListTbls { get; set; }
        public virtual DbSet<FactorSellTbl> FactorSellTbls { get; set; }
        public virtual DbSet<FactorTbl> FactorTbls { get; set; }
        public virtual DbSet<InventoryTbl> InventoryTbls { get; set; }
        public virtual DbSet<ProductTbl> ProductTbls { get; set; }
        public virtual DbSet<RullTbl> RullTbls { get; set; }
        public virtual DbSet<sellFactorTbl> sellFactorTbls { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
